mindmap
  Redis
    基本数据类型
      String
        用来存储INT、float、String
        数据模型
          每一个键值对都是一个 dictEntry（外层的哈希）,通过指针指向key的存储结构和value的存储结构，而且next存储了指向下一个键值对的指针
        存储原理： SDS（Simple Dynamic String） redis自己实现的字符串类型，本质上还是字符数组。 当key是字符串，采用SDS存储。
          编码
            int：存储8个字节的长整型（long,2^63 -1）
            embstr：代表embstr格式的SDS，存储小于44个字节的字符串。
            raw：存储大于44个字节的字符串
            编码升级
              int 数据不再是整数，升级为 raw。
              int 大小超过 long 的范围（2^63 -1）,升级为embstr
              embstr长度超过44个字节，升级为 raw。
              修改 embstr,都会升级为raw。因为 embstr的实现是只读的，因此在对 embstr 对象进行修改时，都会先转化为raw在进行修改。
          结构： 存储不同长度的字符串
            sdshdr5
              存储2^5=32 byte 长度的字符串
            sdshdr8
              存储2^8=256 byte 长度的字符串
            sdshdr16
              存储2^16=65536 byte = 64KB 长度的字符串
            sdshdr32
              存储2^32= 4GB 长度的字符串
            sdshdr64
          为什么使用SDS？ C语言没有字符串类型，只能用字符数组 char［］ 实现
            字符数组必须分配足够的空间，否则可能溢出
            获取字符长度，需要遍历字符数组，时间复杂度是O（n）
            C 字符串长度的变更会对字符数组做内存重分配
            通过从字符串开始到结尾碰到的第一个‘\0’ 来标记字符串的结束，因此不能保存图片、音频、视频、压缩文件等二进制保存的内容，二进制不安全。
          优点
            不用担心内存溢出的问题，如果需要会对SDS扩容
            获取字符串道航渡时间复杂度为O（1），因为定义了len 属性。
            通过“空间预分配”和“惰性空间释放”，防止多次重分配内存。
            判断是否结束的标志是len属性
        redisObject 五种常用的数据类型的任何一种的value都是通过redisObject 存储的，最终redisbject再通过一个指针指向实际的数据结构，比如字符串或者其它。
      Hash 用来存储对各无序的键值对。 最大存储数量2^32 -1（40亿左右）
        Hash的value只能时字符串，不能嵌套其他类型，比如hash或者list。
        问题 1：Hash中的Field不能单独设置过期时间 2：需要考虑数据量分布的问题（Field 非常多的时候，无法分布到多个节点）
        存储原理： hash 的底层可以使用两种数据结构实现： ziplist： OBJ_ENCODING_ZIPLIST（压缩列表） hashtable： OBJ_ENCODING_HT（哈希表）
          ziplist 经过特殊编码，由连续内存块组成的双向链表。 不存储指向上一个链表节点和指向下一个链表节点的指针，而是存储上一个节点长度和当前节点长度。这样读写可能慢一些（需要计算长度），但是可以节省内存。
            Entry的内容：
              未命名
              未命名
                ZIP_STR_06B（0＜＜6）：长度小于等于63字节 ZIP_STR_14B（1＜＜6）：长度小于等于16383字节 ZIP_STR_32B（2＜＜6）：长度小于等于4294967295字节
            什么时候使用ziplist？ 满足两个条件 这两个条件都是可以配置的： hash-max-ziplist-value：64 hash-max-ziplist-entries： 512 如果超过这两个参数的任何一个，存储结构就会转换成 hashtable
              哈希对象保存的键值对数量 ＜ 512个；
              所有的键值对的键和值的字符串长度都 ＜ 64 byte（一个英文字母一个字节）
          hashtable 在hashtable中，又对dictEntry 进行了多层封装。
            结构
              dictEntry
              dictht
              dict
            扩容rehash
              步骤
                为字符 ht［1］哈希表分配空间。ht［1］的大小第一个大于等于ht［0］.used*2的2的N次方幂。eg：第一个使用了10000,那就是16384
                将所有的ht［0］上的节点rehash到ht［1］上，重新计算hash值和索引，然后放入指定的位置。
                当ht［0］全部迁移到ht［1］之后，释放ht［0］的空间，把ht［1］设置为ht［0］表，并创建新的ht［1］，为下次rehash 准备
    分支主题 2
    分支主题 3
