mindmap
  集合
    普通集合
      List
        ArrayList
        LinkedList
        Vector
      Set
        HashSet
        TreeSet
        LinkedHashSet
      Map
        HashMap
          回答思路（jdk1.7和1.8区别入手）
            数据结构（容量、加载因子、扩容阈值）（上1.7，下1.8）
              数组+链表
              数组+链表+红黑树
            获取数据时
              hash值的计算方法（上1.7，下1.8）
                4次位移+5次异或运算
                1次位移+1次异或运算
              数据如何存放（上1.7，下1.8）
                数组+链表：数组冲突，放入到链表
                数组+链表+红黑树：数组冲突，放入到链表，长度大于8时，放入红黑树
                  为什么是8？
            插入数据时
              计算hash值（扰动）
              hash&（length-1）计算数组位置
              数组位置是否冲突
                数据存放在数组中
                链表中
                  是否需要树化
                    插入后，是否需要扩容
                红黑树中
                  插入或者更新数据
            扩容机制
              扩容后的计算方式（上1.7，下1.8）
                重新计算：hashCode（） -＞ 扰动 -＞ hash&（length-1）
                新位置=原位置 or 原位置+旧容量
                  hash的新增位为0，新位置=原位置
                  hash的新增位为1，新位置=原位置+旧容量
              转移数据方式（上1.7，下1.8）
                头插法
                尾插法
        TreeMap
          结构
            使用红黑树存储
        LinkedHashMap
          结构
            LinkedHashMap继承自HashMap，具有HashMap的所有特性；
            LinkedHashMap内部维护了一个双向链表存储所有的元素；
            LinkedHashMap可以用来实现LRU缓存淘汰策略；
        HashTable
    线程安全集合
      ConcurrentHashMap
        ConcurrentHashMap的key可以为空，HashTable不可以
          Hashtable使用的是安全失败机制（fail-safe）：无法判断对应的key是不存在还是为空
        安全失败机制（fail-safe）
          JUC使用这种机制：java.util.concurrent包下的容器都是安全失败，可以在多线程下并发使用，并发修改。
        快速失败（fail—fast）
          util下的集合使用这种机制：检测到 modCount！= expectedmodCount，就会抛出异常
        数据结构
          数组+链表（Segment+HashEntry）jdk1.7
            HashEntry和HashMap不同点：volatile去修饰了他的数据Value还有下一个节点next。
            分段锁技术，其中 Segment 继承于 ReentrantLock
            Segment默认值：16
            get操作不需要加锁，为什么？
              Node的元素val和指针next是用volatile修饰的，在多线程环境下线程A修改因为hash冲突修改结点的val或者新增节点的时候是对线程B可见的。
          数组+链表+红黑树 jdk1.8
            CAS + synchronized
            插入操作
              根据key计算hashCode
              根据hashCode定位Node
              判断是否需要初始化
              如果没有冲突，直接采用CAS尝试写入，失败则自旋保证成功
              如果当前位置的 hashcode == MOVED == -1，则需要进行扩容
              如果超过8，则需要树化
            查询操作
              根据hashCode查询数组位置 -＞ 如果是链表按照链表查找，如果是红黑树按照红黑树查找
        乐观锁与悲观锁
          悲观锁：synchronized和ReentrantLock
          乐观锁：CAS，Version
      ArrayBlockingQueue
        结构
          继承BlockingQueue
          数组结构
          使用ReentrantLock加锁
          使用notFull和notEmpty控制阻塞
          使用takeIndex和putIndex游标定位
      LinkedBlockingQueue
        结构
          继承BlockingQueue
          单链表结构
          使用ReentrantLock加锁
          使用notFull和notEmpty控制阻塞
      PriorityBlockingQueue
        结构
          继承BlockingQueue
          数组结构
          使用ReentrantLock加锁
          使用notEmpty控制阻塞
          使用二叉堆结构
      SynchronousQueue
      ConcurrentLinkedQueue
        结构
          不继承BlockingQueue
          不是阻塞队列
          不能用于线程池
          线程安全
          使用CAS+自旋加锁
      ConcurrentSkipListMap
      DelayQueue
      LinkedTransferQueue
    集合的架构图
