scanPackage=org.linetime.customspring.demo

templateRoot=layouts

#������ʽexpression#
pointCut=public .* org.linetime.customspring.demo.service..*Service.add(.*)
#������
aspectClass=org.linetime.customspring.demo.aspect.LogAspect
#ǰ��֪ͨ�ص�����
aspectBefore=before
#����֪ͨ�ص�����
aspectAfter=after
#�쳣֪ͨ�ص�����
aspectAfterThrow=afterThrowing
#�쳣���Ͳ���
aspectAfterThrowingName=java.lang.Exception