mindmap
  JVM
    Java对象区域与Java对象创建方法
      Java对象区域
        Java堆
        方法区
        程序计数器
        虚拟机栈
          局部变量表
        本地方法栈
        运行时常量池
        直接内存
      Java对象创建方法
    对象存活判定算法
      引用计数法
      可达性分析算法
        可作为GC Roots的对象
    垃圾收集算法
      标记-清除
      复制
      标记-整理
      子主题 4
    对象分配策略
      对象优先在Eden区分配
      大对象直接进入老年代
      长期存活的对象将进入老年代
      动态对象年龄判定
      空间分配担保
    FullGC触发条件
      调用System.gc（）
      老年代空间不足
      空间分配担保失败
      JDK 1.7及以前的永久代空间不足
      Concurrent Mode Failure
    7种垃圾回收器
      新生代
        Serial
        ParNew
        Parallel Scavenge
          吞吐量优先
      老年代
        Serial Old
        Parallel Old
          吞吐量优先
        CMS
          cpu资源敏感
          浮动垃圾
          空间碎片
      G1
        横跨整个堆内存，独立区域（Region）
        建立可预测的时间模型
        避免全堆扫描——每个Region维护了一个与之对应的Remembered Set
      并行和并发
      Minor GC 和 Full GC
    如何进行GC优化
    虚拟机类加载机制
      加载
        通过一个类的全限定名来获取定义此类的二进制字节流。
        将这个字节流所代表的静态存储结构转化为方法区的运行时存储结构。
        在内存中生成一个代表这个类的java.lang.Class对象，作为方法区这个类的各种数据的访问入口。
      验证
        文件格式验证
        元数据验证
        字节码验证
        符号引用验证
      准备
        为类变量分配内存
        设置类变量初始值
      解析
        7类符号引用
      初始化
      使用
      卸载
    类加载器
      双亲委派模型
        启动类加载器（Bootstrap ClassLoader）
        扩展类加载器（Extension ClassLoader）
        应用程序类加载器（Application ClassLoader）
        优点
      线程上下文类加载器
        SPI
          父类加载器请求子类加载器去完成类加载器的动作，这种行为实际上就是打通了双亲委派模型的层次结构来逆向使用类加载器.
