mindmap
  Synchronized
    为什么使用Synchronized
      在并发编程中存在线程安全问题，主要原因有：1：存在共享数据；2：多线程操作共享数据。 关键字 Synchronized 可以保证在同一时刻，只有一个线程可以执行某个方法或者某个代码块，同事 Synchronized 可以包含保证一个线程的变化可见，即可以代替 Volatile。
    应用方式
      Java中每一个对象都可以作为锁，这是 Synchronized 实现同步的基础。 1：普通同步方法（实例方法），锁是当前实例对象，进入同步代码钱需要获取当前实例的锁； 2：静态同步方法，锁是当前类的 class 对象，进入同步代码前需要获得当前类对象的锁； 3：同步方法块，锁是括号里面的独享，对给定对象加锁，进入同步代码块前需要获取给定对象的锁。
    实现原理
      从 JVM 规范中可以看到 Synchronized 的实现原理：JVM 基于进入和退出 Monitor 对象来实现方法和代码块的同步，但两者的实现细节不一样。 monitorenter 指令是在编译后插入到同步代码块的开始位置，而 monitorexit 指令是插入到方法结束处和异常处，JVM 要保证每一个 monitorenter 必须有对应的 monitorexit 与之配对。任何对象都有一个 monitor 与之关联，当且一个 monitor被持有后，它将处于锁定状态。线程执行到 monitorenter指令时，将会尝试获得对象所对应的monitor 的所有权，即尝试获取对象的锁。
    对象的锁
      synchronized 用的锁是存在 Java 对象头里的。如果对象是数组类型，则虚拟机用 3个字宽存储对象头，如果对象是非数组类型，则用2字宽存储对象头。在32 位虚拟机中，1字宽=4字节=32 bit
