mindmap
  数据结构
    红黑树
      时间复杂度
        查找：O（logN）
        插入：O（logN）
        删除：O（logN）
    跳表
      二分查找的有序链表
      跳表的插入
        根据投硬币的方式，决定8这个元素要占据的层数
        找到8的位置，链表插入方法
      跳表的删除
        找到各层中包含元素x的节点
        按照链表方法删除
      时间负责度
        单链表
          查询的时间复杂度为O（n），插入、删除操作需要先找到对应的位置，所以插入、删除的时间复杂度也是O（n）
        跳表
          跳表查询、插入、删除的时间复杂度为O（log n），与平衡二叉树接近
    B树
      时间复杂度：同B+树
      定义
        根结点至少有两个子女
        每个中间节点都至少包含ceil（m / 2）个孩子，最多有m个孩子
        每一个叶子节点都包含k-1个元素，其中 m/2 ＜= k ＜= m
        所有的叶子结点都位于同一层
        每个节点中的元素从小到大排列
    B+树
      时间复杂度
        查找：O（logN）
        插入：O（logN）
        删除：O（logN）
    二叉查找树
      时间复杂度
        查找：logn，最差 n
        插入和删除与查找相同
    二叉平衡树
      时间复杂度
        查找：logn
        插入：logn
        删除：2logn
    排序算法
      冒泡
        O（n^2）
        稳定
      选择
        O（n^2）
        不稳定
      插入
        O（n^2）
        稳定
      归并
        O（nlogn）
        稳定
      快速
        O（nlogn）
        不稳定
      堆
        O（nlogn）
        稳定
    区别
      数据结构
        B+树数据只出现在叶子结点，B树每个结点都包含了数据；
        B+树叶子结点之间用指针连接
      查询对比
        B+树单一节点存储的元素更多，使得查询的IO次数更少，所以也就使得它更适合做为数据库MySQL的底层数据结构了
        B+树所有的查询都要查找到叶子节点，查询性能是稳定的
        B+树所有的叶子节点形成了一个有序链表，更加便于查找
